version: '3.7'

services:
  postgres-db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: scratch_fhir
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - my-network

  spring-backend:
    build:
      context: ./backend/scratch.fhir
    ports:
      - "8443:8443"
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - postgres-db

  react-frontend:
    build:
      context: ./frontend
    ports:
      - "443:443"
    networks:
      - my-network

networks:
  my-network:
